version: '3'
services:
  tf-flask:
    build: tf-flask/.
    ports:
     - "5023:5000"
    command: ["python","/code/run.py"]
  nginx-ci:
    image: "kunyang/kunyang_docker_php:0.1"
    volumes:
     - ./CodeIgniter-3.1.6:/var/www/html
    ports:
     - "8021:80"
    command: ["bash","/start.sh"]

